version: '3'
services:
  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=employee_app_password
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata

  app:
    build: .
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle:1521:XE
      - SPRING_DATASOURCE_USERNAME=employee_app
      - SPRING_DATASOURCE_PASSWORD=employee_app_password
    depends_on:
      - oracle

volumes:
  oracle-data:
